---
- name: Execute post hardening scan
  ansible.builtin.command: >
    oscap xccdf eval
    --profile {{ hardening_scap_profile }}
    --results {{ hardening_execution_workdir }}/{{ hardening_post_scan_xml }}
    --report {{ hardening_execution_workdir }}/{{ hardening_post_scan_html }}
    {{ hardening_scap_datastream }}
  register: post_scan_result
  changed_when: false
  failed_when: post_scan_result.rc not in [0, 2]