---

- name: Package reports for download from AAP UI
  ansible.builtin.archive:
    path: "{{ hardening_remote_workdir }}"
    dest: "/runner/artifacts/hardening_reports.tar.gz"
    format: gz
  delegate_to: localhost
  run_once: true

- name: Remove prerequisite packages
  ansible.builtin.package:
    name: "{{ hardening_required_packages }}"
    state: absent
  when: hardening_remove_prereqs_at_end | bool

- name: Remove remote execution directory
  ansible.builtin.file:
    path: "{{ hardening_execution_workdir }}"
    state: absent
  when: not hardening_keep_remote_artifacts_after_copy | bool

- name: Remove local staging directory on execution node
  ansible.builtin.file:
    path: "{{ hardening_controller_stage_dir }}/rhel{{ ansible_distribution_major_version }}/"
    state: absent
  when: not hardening_keep_remote_artifacts_after_copy | bool


  